version: '3'

services:

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    mem_limit: 128m
    networks:
      - bravonet

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -Ubravo -d alarm_bot" ]
      interval: 10s
      timeout: 5s
      retries: 100
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bravo
      - POSTGRES_PASSWORD=bravo
      - POSTGRES_DB=alarm_bot
    mem_limit: 128m
    networks:
      - bravonet
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"

  alarm-bot:
    image: bravo/alarm-bot:latest
    container_name: alarm-bot
    restart: always
    mem_limit: 128m
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=alarm_bot
      - SPRING_DATASOURCE_USERNAME=bravo
      - SPRING_DATASOURCE_PASSWORD=bravo
      - TELEGRAM-BOT_TOKEN=
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bravonet

volumes:
  redis-volume:

networks:
  bravonet:
